[package]
name = "myquick"
version = "0.1.0"
authors = ["taiki.yoshinaka <taiki.yoshinaka@agc.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "*"